version: "3"

services:
  ftso:
    image: bbftso/ftsojs:lean
    volumes:
     - ./logs:/var/log
    environment:
     - CC_API_KEY=
     - COINAPI_KEY=
     - CMC_PRO_API_KEY=
     - PRICE_SOURCE=
     - RPC_NODE_URL=
     - FTSO_PRIVATE_KEY=
     - GMAIL_USER=
     - GMAIL_PASSWORD=
     - ERROR_MAIL_LIST=
    command: /bin/bash -c ./ftso_start.sh